export const POLYGONSCAN_API_KEY = process.env.POLYGONSCAN_API_KEY!
export const POLYGON_MUMBAI_RPC_PROVIDER = process.env.POLYGON_MUMBAI_RPC_PROVIDER!

export const SUPABASE_URL = process.env.SUPABASE_URL!
export const SUPABASE_SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE!
